### ISSUE TITLE
Test for main language fails in preamble

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#532] opened 2022-03-23 10:09 UTC
The following document writes “german is not loaded french is loaded” to the log file. However, both have been loaded.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{german}
\setotherlanguage{french}

\iflanguageloaded{german}{\message{german is loaded}}{\message{german is not loaded}}
\iflanguageloaded{french}{\message{french is loaded}}{\message{french is not loaded}}

\begin{document}
\end{document}
```

**Comment by jspitz** [comment] 2022-03-23 11:27
Language loading happens AtBeginDocument. Maybe these test should account for that.

**Comment by wehro** [comment] 2022-03-23 11:33
I would prefer to be able to test in the preamble. This way it would be easier for other language-related packages to do language settings in the preamble.

**Comment by jspitz** [comment] 2022-03-23 12:23
You can defer the tests to `\AtBeginDocument` in the preamble yourself. My idea would by that the tests automatically do that when used in the preamble.

**Comment by jspitz** [comment] 2022-03-23 12:38
Would something like this do your you?
```diff
diff --git a/tex/polyglossia.sty b/tex/polyglossia.sty
index 3ef5bb5..bf3b4f0 100644
--- a/tex/polyglossia.sty
+++ b/tex/polyglossia.sty
@@ -2083,7 +2083,7 @@
 
 % Test if language is loaded
 \newcommand*\iflanguageloaded[3]{%
-  \clist_if_in:NeTF \xpg@loaded{#1}{#2}{#3}%
+   \AfterPreamble{\clist_if_in:NeTF \xpg@loaded{#1}{#2}{#3}}%
 }
 
 % Same for babellanguage is loaded
lines 1-13/13 (END)

```

**Comment by jspitz** [comment] 2022-03-23 12:51
> Would something like this do your you?

A respective fix has been committed (also for the other tests). Please check.

**Comment by wehro** [comment] 2022-03-23 22:23
Yes, this code seems to be fine for me. Thanks!

**Closed** 2022-03-27 07:47 UTC
Labels: FIXED IN DEV

**Comment by alexpovel** [comment] 2022-04-29 14:07
Hi!

This change broke a document of mine. Skip to the bottom for the gist.

## Context

The document is a thesis template and aims to support both the English and German languages. The user specifies these as a regular class option: `\documentclass[language=english]{acp}` (or `language=german`; the class name is `acp`). I then dispatch on that to dynamically load the main language, using `\expandafter\setdefaultlanguage\expandafter{\acp@language }` further down in the custom class aka the preamble.

In any case, the *other*, non-main language is also supposed to be supported, so consumers of my class can switch languages freely without having to do any work like declaring languages. English and German are supposed to "just work".

This is done by inspecting whatever language was loaded as the main one and setting the *other* one as an alternative language. The full code concerning `polyglossia` is:

```latex
\RequirePackage{polyglossia}% Language rules. Replacement for babel in lualatex
    % Expand this properly; the version without \expandsafters does not work fully.
    % It works this way:
    % The first \expandafter is seen, so the following \setdefaultlanguage is not
    % expanded and skipped.
    % Next, the second \expandafter is looked at. It sees the token { next, saving it
    % for later.
    % \acp@language is then expanded fully, to the current language.
    % What is left is a properly working string, \setdefaultlanguage{<language string>}
    \expandafter\setdefaultlanguage\expandafter{\acp@language }

    % Whatever main language (setmainlanguage = setdefaultlanguage) was loaded, we want
    % the "other" one (since we expect only English and German) to be available as a
    % secondary language. This is very convenient if for example a thesis is in English,
    % but certain parts have to be in German, e.g. for legal reasons. A simple switch
    % \begin{german} ... \end{german} would then achieve that.
    %
    % Note that we can also do \setotherlanguages{english, german, ...}, for a
    % one-stop-shop, but that would also mean loading the main language as an "other"
    % language, which has "trouble" written all over it. Therefore, choose this weak/
    % somewhat manual approach.
    \iflanguageloaded{english}{%
        \setotherlanguage{german}%
    }{%
        % Nested ifs are ugly, but case-switch is not available and
        % flat, subsequent ifs could load the first language both as a main and
        % as an "other" language
        \iflanguageloaded{german}{%
            \setotherlanguage{english}%
        }{%
            % False: do nothing
        }
    }%
```

The original comments with my shoddy understanding of LaTeX internals were left in. Now, from the `etoolbox` documentation on `AfterPreamble`:

> This hook is a variant of `\AtBeginDocument` which may be used in both the preamble and the document body. When used in the preamble, it behaves exactely like `\AtBeginDocument`. When used in the document body, it immediately executes its *code* argument. `\AtBeginDocument` would issue an error in this case. This hook is useful to defer code which needs to write to the main aux file.

So I guess the issue is that whatever executes from `iflanguageloaded` now occurs at the document beginning, but `setotherlanguage` and others can only occur in the preamble. At least, that's the error message I got after first trying to compile using TeXLive 2022 (with `polyglossia` version `1.56`):

```text
(/usr/local/texlive/2022/texmf-dist/tex/latex/polyglossia/gloss-german.ldf
(./babelsh.def

! LaTeX Error: Can be used only in preamble.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.359 ...dOfPackage{\let\bbl@restoreactive\@gobble}}
```

(the line 359 info was entirely unhelpful, but that's just LaTeX for you)

## Gist

If fixed it this way for now:

```latex
\RequirePackage{polyglossia}% Language rules. Replacement for babel in lualatex
    \expandafter\setdefaultlanguage\expandafter{\acp@language }
    \setotherlanguages{english,german}
```

It compiled fine. However, in the past I *assumed* (see original comments above) loading a *main* language and then loading *that same language* again as an "*other*" language is no bueno. Can you confirm or deny this is fine to do? It would greatly simplify the required code, but seems brittle? (If it's anything like other languages, already loaded modules/languages would simply be skipped?)
