### ISSUE TITLE
Inconsistent \textsc with certain fonts

### ISSUE THREAD

**Issue by dustalov** [reutenauer/polyglossia#429] opened 2020-06-21 16:14 UTC
I am using Polyglossia in a document with two languages, English and Russian. I noticed that in some fonts `\textsc` stops working properly if the selected language is Russian. Initially, I thought this issue was caused by plk/biblatex#1017, but then I managed to produce a simpler MWE.

```latex
\documentclass[varwidth]{standalone}

\usepackage{polyglossia}
\setmainfont{Libertinus Serif} % OK
% \setmainfont{FreeSerif} % not OK
% \setmainfont{XCharter} % not OK
\setmainlanguage{english}
\setotherlanguage{russian}

\begin{document}

\textsc{b}\begin{russian}\textsc{b}\end{russian}

\end{document}
```

When the Libertinus Serif font is used, everything is fine:

![bb1.pdf](https://user-images.githubusercontent.com/40397/85229440-49cf4780-b3f2-11ea-9151-b0a8d3e71c13.png)

However, when the font is FreeSerif ([gnu-freefont](https://ctan.org/pkg/gnu-freefont) in CTAN) or XCharter ([xcharter](https://ctan.org/pkg/xcharter) in CTAN), the second `b` is rendered without small-caps.

![bb2.pdf](https://user-images.githubusercontent.com/40397/85229506-a894c100-b3f2-11ea-8c7f-19cf667c31de.png)

Is it possible to avoid this inconsistency without changing the language or font?

**Comment by jspitz** [comment] 2020-06-21 16:53
Workaround is
```tex
\newfontfamily\russianfont{FreeSerif}
```

**Comment by dustalov** [comment] 2020-06-21 16:57
Thank you! A more generic `\newfontfamily\cyrillicfont{FreeSerif}` works, too, but can it be avoided?

**Comment by jspitz** [comment] 2020-06-21 16:58
> Thank you! A more generic `\newfontfamily\cyrillicfont{FreeSerif}` works, too, but can it be avoided?

No.

**Comment by dustalov** [comment] 2020-06-21 16:59
Why? These letters are Latin.

**Comment by jspitz** [comment] 2020-06-21 17:07
Don't know why. Probably a bug or deficiency in polyglossia's font setup.

**Comment by jspitz** [comment] 2020-06-22 06:59
The problem is precisely that Latin is mixed in here. When switching to russian, `polyglossia` internally switches to internal `\russian@font@rm`, which in the case here (since `\russianfont` or `\cyrillicfont` have not been explicitly defined) is automatically defined by `polyglossia` as (simplified)
```tex
\newfontfamily\russian@font@rm[Script=Cyrillic]{FreeSerif}
```
The crucial setting is the `Cyrillic` script option. With this, Latin smallcaps are not set correctly. Therefore, only `\newfontfamily\russianfont{FreeSerif}` works (since the default script `Latin` is used), not the (correct) setting `\newfontfamily\russianfont[Script=Cyrillc]{FreeSerif}`. I suppose, as you suspected, this has to to with the font coverage.

Since the `Cyrillic` script option is correct and needed, I doubt we can do anything here. We cannot switch to Latin inside Russian automatically if Latin characters occur. As to you use case, I suggest you either switch to a Latin language (such as English) for the Latin passages or use `\normalfontlatin`, as in:

```tex
% !TeX TS-program = xelatex
\documentclass[varwidth]{standalone}

\usepackage{polyglossia}
%\setmainfont{Libertinus Serif} % OK
\setmainfont{FreeSerif} % not OK
% \setmainfont{XCharter} % not OK
\setmainlanguage{english}
\setotherlanguage{russian}

\begin{document}

\textsc{b}\begin{russian}{\normalfontlatin\textsc{b}}\end{russian}

\end{document}
```

Marking WONTFIX.

**Closed by jspitz** 2020-06-22 06:59 UTC
