### ISSUE TITLE
Idea: Digraphs in Croatian definitions

### ISSUE THREAD

**Issue by ivankokan** [reutenauer/polyglossia#216] opened 2019-01-23 11:59 UTC
Hi @reutenauer. This is not really an issue but an idea to improve the Croatian definitions.

Motivated by [this discussion on tex.stackexchange](https://tex.stackexchange.com/questions/397937/proper-digraphs-handling-and-rendering), I was wondering would it be correct to replace `l` + `j` within `\def\chaptername{Poglavlje}` with the Unicode `ǉ` ([U+01C9](https://www.compart.com/en/unicode/U+01C9))? If it would, I will make all such necessary changes in my fork and submit PR.

Remark. Not all consecutive appearances of `l` and `j` should be treated as `ǉ`, the same holds for other two digraphs. (Beware that the comment within my code on tex.stackexchange discussion saying `% ...and these consecutive characters will be automatically rendered as U+01C6` is not so correct.) Do you maybe know are there any predefined XeLaTeX/LuaLaTeX definitions for that when using Croatian (not just in polyglossia context), as I would like to check and verify them?

On the other hand, from the tex.stackexchange discussion I conclude it is not feasible to achieve auto-replacement with digraphs (and using two separate characters is the only way to go). Maybe @jbezos can comment on this from babel/LaTeX perspective?

Kind regards, Ivan

**Comment by ivankokan** [comment] 2019-07-23 22:42
Hi,

Analyzing the following MWE in Latin Modern Roman vs Arial variants...

\documentclass{article}
\usepackage{fontspec}
\setmainfont{Latin Modern Roman} % Arial
\usepackage{polyglossia}
\setmainlanguage{croatian}

\begin{document}
poglavlje -Ǉǈǉ- -Ǆǅǆ- -Ǌǋǌ- poglavlje
\end{document}

I got this:
![image](https://user-images.githubusercontent.com/1058211/61752122-e46e7300-adaa-11e9-9534-ba58c5b801b8.png)
![image](https://user-images.githubusercontent.com/1058211/61752168-07992280-adab-11e9-9d5c-d46b115b3489.png)

It seems that none of three Croatian digraphs (`U+01C4`-`U+01CC`) is present in Latin Modern, very surprising. Really, none is given in the list: http://texdoc.net/texmf-dist/doc/fonts/lm/lm-info.pdf.

Would "digraph construction" explained here (https://tex.stackexchange.com/a/398084/115879) be appropriate for `polyglossia` definition files, or I should quit my original idea?

Kind regards, Ivan

**Comment by ivankokan** [comment] 2019-08-01 22:37
Hi,

I managed to get the following
![image](https://user-images.githubusercontent.com/1058211/62331798-563a7100-b4bd-11e9-90e1-ceb32eacef9a.png)
utilizing primitive `\iffontchar` and package `newunicodechar`, e.g.:
```
\newunicodechar{Ǉ}{\iffontchar\font`Ǉ{\color{green}Ǉ}\else{\color{red}LJ}\fi}
```

Hopefully I can wrap up the concept into Pull request by the weekend.

Kind regards, Ivan

**Comment by ivankokan** [comment] 2019-08-23 12:37
I will park the work on this until improvements on switching languages are made.

**Comment by reutenauer** [comment] 2019-08-23 13:11
Hi Ivan,

Sorry about the late reply; I’m a little doubtful, I have to say.  What exactly do you want to use the Unicode digraphs for?  From what I understood they were introduced because there were apparently Latin fonts in Yugoslavia, in the 70s or 80s, that matched the Serbian Cyrillic alphabet character-for-character, hence they had a glyph position for љ and њ (displayed as lj and nj).  Because Unicode from its early days was designed to be able to transcode any existing encoding one-to-one, they included lj and nj as characters; but these were not even present in YUSCII or any other Yugoslav encodings, and were instead just Latin representations of Cyrillic characters in some font.

In any case, I wouldn’t use the digraphs in any definition in Polyglossia, for the pragmatic reason that they’re very poorly supported, as you point out yourself.  Maybe we can implement some kind of support for them, but it’s not clear to me what it should be.

Best,

Arthu

**Comment by jspitz** [comment] 2019-09-13 09:43
Shall we close this, then?

**Comment by ivankokan** [comment] 2019-09-13 09:50
Please keep it open until I prepare some demo/POC.

**Comment by reutenauer** [comment] 2019-10-31 14:51
Any progress?

**Comment by ivankokan** [comment] 2019-11-23 14:36
> Any progress?

Next week.

**Comment by jspitz** [comment] 2019-11-24 16:24
FWIW the following will do what you want. It outputs the ligature if it is in the font, else the separate glyphs:

```tex
\def\captionscroatian{%
  \def\chaptername{Poglav\xpg@cro@lig{01C9}{lj}e}%
}

\def\xpg@cro@lig#1#2{%
  \ifluatex%
    \expandafter\ifnum\directlua{polyglossia.check_char(0x#1)} > 0\char"#1%
    \else #2%
    \fi%
  \else%
    \ifnum\XeTeXcharglyph"#1 > 0\char"#1%
      \else #2%
    \fi%
  \fi%
}
```

For the other two cases, use `\xpg@cro@lig{01C6}{dž}` and `\xpg@cro@lig{01CC}{nj}`

If you don't need it in the captions only but also want to provide it for the users, I'd recommend to implement babelshorthands, e.g., `"n`, `"l` and `"d`.

**Comment by jspitz** [comment] 2019-11-25 08:36
As of e2f6667b8e0428 it is even easier. Just use
```tex
\def\chaptername{Poglav\charifavailable{01C9}{lj}e}%
```

**Comment by jspitz** [comment] 2019-11-25 10:48
@ivankokan please try the modified gloss-croatian from https://raw.githubusercontent.com/jspitz/polyglossia/master/tex/gloss-croatian.ldf

This implements the idea above plus babelshorthands for the ligatures in question. The following outputs the ligatures if the font has them and the normal characters if not:

```
\documentclass[10pt,a4paper]{article}
\usepackage{polyglossia}
\setmainlanguage[babelshorthands=true]{croatian}
\setmainfont{DejaVu Serif}
\begin{document}
	
	\chaptername
	"DZ "Dz "dz
	"LJ "Lj "lj
	"NJ "Nj "nj
	
\end{document}
```
I've also implemented some other general shorthands which are supposedly useful for Croatian as well.

Note that this requires current polyglossia master.

**Comment by ivankokan** [comment] 2019-11-26 11:10
Hi everyone.

Considering that some implementation has been done on this matter, let me start sharing my thoughts on how things should work...

### Using Croatian Unicode digraphs in general
If the language context is not Croatian, they should be rendered as such with respect to the used font. This can result either with:
- correct glyphs ✔️
- missing glyphs ⚠️ (check my comment https://github.com/reutenauer/polyglossia/issues/216#issuecomment-514410273): fallback to consecutive characters must be automatically done ✔️
- invalid glyphs (e.g. check the comment for `-dRENDERTTNOTDEF` in https://www.ghostscript.com/doc/current/Use.htm, I have such Arial font on my system): no proper way to detect this as glyph is really present in the font, context is not Croatian => leave it (as bad) as is. ❗️

If the language context is Croatian, user will recognize the "invalid glyphs" case and should have an option to activate fallback to consecutive characters (inline option, declaration, whatever, as things might change using different fonts throughout the document).

If I understand what has been implemented so far, "invalid glyphs" case is not implemented as described here?

**Comment by ivankokan** [comment] 2019-11-26 11:23
### Shorthands
Good to have them! (I have not tested it yet, though.) However, I would like to have them disabled by default since it is not a common way when typesetting Croatian and users might get confused why did some quotemarks "disappear".

**Comment by jspitz** [comment] 2019-11-26 12:14
Note that `babelshorthands` are always disabled by default

**Comment by jspitz** [comment] 2019-11-26 12:16
> If I understand what has been implemented so far, "invalid glyphs" case is not implemented as described here?

I don't know. I need a test case for that (or you need to test yourselves).

An option `disableligatures` can be added easily, though, if that's what you want.

**Comment by jspitz** [comment] 2019-11-26 12:19
> Where did you find the motivation for non-digraph shorthands? As mentioned, shorthands in Croatian typesetting are not common and if having any, I would like to have only those for digraphs (non-active by default).

Don't you think the shorthands for breakable slash and the hyphenation fine-tuning could be of interest to some users? I think they are of general value for alphabetic scripts.

**Comment by jspitz** [comment] 2019-11-26 12:48
> An option `disableligatures` can be added easily, though, if that's what you want.

Done at https://github.com/jspitz/polyglossia/commit/f54f601dcaca6556dbf52a4bb9866981d89fa9ea

**Comment by jspitz** [comment] 2019-11-26 13:40
I've now merged in my changes, so you can test more easily. Please test and report back.

**Comment by jspitz** [comment] 2019-12-09 15:40
Any news?

**Comment by ivankokan** [comment] 2019-12-17 07:40
Hi. I had to focus on some other things. This week seems to be good for `polyglossia` testing.

**Comment by jspitz** [comment] 2020-01-29 11:52
This feature is in v1.47, which is on its way to release.

**Closed by jspitz** 2020-01-29 11:52 UTC
Labels: Feature request

**Comment by ivankokan** [comment] 2020-01-29 12:10
@jspitz Yesterday I finally synced my fork with the upstream and started to test. I see no risk in including what is implemented so far in the new release. But definitely I will finish my testing in proper way, hopefully everything will be fine.

**Comment by jspitz** [comment] 2020-01-29 12:28
Well, the release is finished, so we do not discuss anymore at this point if and what will be included.
