### ISSUE TITLE
csquotes `MakeOuterQuote` does not work

### ISSUE THREAD

**Issue by sorashi** [reutenauer/polyglossia#592] opened 2023-05-29 07:55 UTC
This seems to be the exact same issue as #421 that was supposed to be fixed in polyglossia 1.50 (if I understand correctly). Now I'm on 1.62 and the issue persists.

Reproduce:

```tex
\documentclass[12pt, a4paper]{report}
\usepackage{polyglossia}
\setdefaultlanguage[babelshorthands=false]{czech}

\usepackage{csquotes}
\MakeOuterQuote{"}

\begin{document}
Testing "quotes".

Testing \enquote{quotes}.

Testing "`quotes"'.
\end{document}
```
Result:
![image](https://github.com/reutenauer/polyglossia/assets/6270283/b38684d7-3596-4aed-ab28-9184665b9311)

Expected:
![image](https://github.com/reutenauer/polyglossia/assets/6270283/41116137-4121-4f45-ad54-7a6486961a2d)

(The third test is to see that babelshorthands are really off)

Am I doing something wrong or is the issue back?

**Comment by jspitz** [comment] 2023-05-29 13:52
The issue came back with d2f6bf39da62a8dd6 which was necessary to fix a different bug. The only advise for now is to use a different character for the `csquotes` purpose.

**Comment by jspitz** [comment] 2023-05-31 08:50
I have fixed it differently now. I have introduced a central command to activate and deactivate shorthands in the package. This tracks whether we have ourselves activated shorthands and only deactivates them if this was the case, thus leaving
`"` active it is was activated by another package (such as `csquotes`).

The only gloss file I have not touched is `latin`, as this has not only `"`-based shorthands and also handles them generally differently. So the problem still persists if `latin` is involved.

@wehro You might want to have a look at this and check whether and what needs to be done for `latin`. Of course, extending the command to other shorthand characters (via an optional argument) is principally possible

In any case, now the above example yields:
![grafik](https://github.com/reutenauer/polyglossia/assets/4538783/bfd63a04-dd92-4ffd-952f-c7c25013285e)
(which is the expected outcome IMHO as the quotes are also cs-ones in the third case)

and #320 remains fixed.

**Comment by jspitz** [comment] 2023-06-01 05:50
Should I extend `\xpg@activate@shorthands` to take an optional argument, or are you doing that in your PR anyway?

**Comment by jspitz** [comment] 2023-06-01 06:50
> Should I extend `\xpg@activate@shorthands` to take an optional argument, or are you doing that in your PR anyway?

Well, I went ahead and did that. You can now use `\xpg@activate@shorthands[']` and `\xpg@deactivate@shorthands[']`. Without optional argument, `"` is presumed.

As for the PR, note that I will have to do a release soon after the new LaTeX version has been published (which will be in the coming days), since we have a regression that needs to be addressed.

**Closed** 2023-06-10 06:48 UTC
