### ISSUE TITLE
no hyphenation for hyphen-separated compound words

### ISSUE THREAD

**Issue by intractabilis** [reutenauer/polyglossia#446] opened 2020-09-25 03:15 UTC
In Russian there are compound words in which two parts are separated with a hyphen. Polyglossia doesn't hyphenate these words. Even adding these words to `\pghyphenation` doesn't help.

MWE:
```LaTeX
\documentclass[12pt, letterpaper]{scrbook}

\usepackage[autopunct]{csquotes}
\usepackage{polyglossia}

\setdefaultlanguage[babelshorthands = true]{russian}
\SetLanguageKeys{russian}{
    hyphenmins  = {2, 2}
  , indentfirst = true
  }

% it's easier to notice with Garamond
\setmainfont{EB Garamond}[
    Numbers    = {Proportional, Uppercase}
  , RawFeature = {+ss6}
  ]
\newfontfamily\cyrillicfont[
    Numbers           = {Proportional, Uppercase}
  , RawFeature        = {+ss6}
  ]{EB Garamond}

\setsansfont{FreeSans}
\newfontfamily\cyrillicfontsf{FreeSans}
\setmonofont{FreeMono}
\newfontfamily\cyrillicfontmono{FreeMono}

\KOMAoptions{fontsize = 12, BCOR = 8.25mm}
\KOMAoptions{DIV = 14}

\pghyphenation{russian}{
    фран-цу-жен-кою
    гу-вер-нант-кой
    фран-цу-жен-кою-гу-вер-нант-кой
}

\begin{document}

Все счастливые семьи похожи друг на друга, каждая несчастливая семья
несчастлива по-своему.

Всё смешалось в доме Облонских. Жена узнала, что муж был в связи с бывшею в их доме
француженкою-гувернанткой, и объявила мужу, что не может жить с ним в одном доме. Положение это
продолжалось уже третий день и мучительно чувствовалось и самими супругами, и всеми членами семьи, и
домочадцами. Все члены семьи и домочадцы чувствовали, что нет смысла в их сожительстве и что на
каждом постоялом дворе случайно сошедшиеся люди более связаны между собой, чем они, члены семьи и
домочадцы Облонских. Жена не выходила из своих комнат, мужа третий день не было дома. Дети бегали по
всему дому, как потерянные; англичанка поссорилась с экономкой и написала записку приятельнице,
прося приискать ей новое место; повар ушел вчера со двора, во время самого обеда; чёрная кухарка и
кучер просили расчёта.
\end{document}
```

This example produces an overfull box in the second line, because `француженкою-гувернанткой` is not hyphenated:
![изображение](https://user-images.githubusercontent.com/45959195/94222432-2f4db400-fea2-11ea-9a10-7e169099cf8f.png)

```
Overfull \hbox (35.25482pt too wide) in paragraph at lines 41--50
[]\TU/EBGaramond(1)/m/n/12 Всё сме-ша-лось в до-ме Об-лон-ских. Же-на узна-ла, что муж был в свя-зи с быв-шею в их до-ме француженкою-
```

If you change the hyphen in `француженкою-гувернанткой` to a space (which is ungrammatical), the hyphenation starts working and the overfull box disappears.

**Comment by jspitz** [comment] 2020-09-25 11:53
This rather looks like a problem in the hyphenation patterns. @reutenauer?

**Comment by jspitz** [comment] 2020-09-25 12:52
Actually, on a closer look, this seems correct: LaTeX by default only hyphenates at the hyphen if a word has a fixed hyphen (this is an anglo-centric rule).

The solution is to use the babel shorthand `"=` (undocumented for Russian), i.e., `француженкою"=гувернанткой` rather than `француженкою-гувернанткой`). This hyphenates earlier in the word:
![grafik](https://user-images.githubusercontent.com/4538783/94269267-bbadb480-ff3e-11ea-9025-e4534f082146.png)

**Comment by jspitz** [comment] 2020-09-25 12:58
Not a bug. Closing.

**Closed by jspitz** 2020-09-25 12:58 UTC

**Comment by intractabilis** [comment] 2020-09-25 14:01
> LaTeX by default only hyphenates at the hyphen

But this is not about hyphenation at the hyphen. It doesn't hyphenate anywhere. The documentation contrasts `"=` and `\-`, the latter being described as disabling hyphenation patterns, not `"=` and `-`.

**Comment by jspitz** [comment] 2020-09-25 14:08
As your own example above shows, it _hyphenates_ at the hyphen with -. Your example was hyphenated
```
француженкою-
гувернанткой
```
wasn't it? See line two/three in your image above.

This is how TeX does it by default. With "= TeX will hyphenate also anywhere else in the word, if a hyphen breakpoint is defined.

**Comment by jspitz** [comment] 2020-09-25 14:10
> The documentation contrasts `"=` and `\-`, the latter being described as disabling hyphenation patterns, not `"=` and `-`.

No, the documentation contrasts `"-` and `\-` (and `"=` and `-`)

**Comment by intractabilis** [comment] 2020-09-25 14:12
Ok, got it. Thank you. Very inconvenient, but it's not a polyglossia fault.

> No, the documentation contrasts `"-` and `\-` (and `"=` and `-`)

My English comprehension fools me? Where is `"=` vs `-`?

![изображение](https://user-images.githubusercontent.com/45959195/94277382-576b0080-fefe-11ea-9b3f-b824c2da99c1.png)

**Comment by jspitz** [comment] 2020-09-25 14:16
> My English comprehension fools me? Where is `"=` vs `-`?

As I wrote in https://github.com/reutenauer/polyglossia/issues/446#issuecomment-698910714 this was not yet documented for Russian (but I have meanwhile done that with https://github.com/reutenauer/polyglossia/commit/8ad842523ae0882000528cc4f4c5ad9dba1fa51f)

**Comment by intractabilis** [comment] 2020-09-25 14:24
Ah, I mixed `"-` and `"=`. Thank you for taking care of that.

**Comment by intractabilis** [comment] 2020-10-04 01:34
I found a more elegant solution. It turned out that words containing a hyphen have to be added to the hyphenation patterns with a `=` symbol. So a solution that in a true spirit of LaTeX separates the content from the presentation is
```LaTeX
\pghyphenation{russian}{
    фран-цу-жен-кою=-гу-вер-нант-кой
}
```
