### ISSUE TITLE
\setotherlanguages fails with babel update

### ISSUE THREAD

**Issue by bdtc** [reutenauer/polyglossia#400] opened 2020-03-24 10:52 UTC
Similar to [Issue 399](https://github.com/reutenauer/polyglossia/issues/399), \setotherlanguages now fails with \bbl@cs undefined, as of babel update 2020/03/22.

**Comment by jspitz** [comment] 2020-03-24 11:22
Can you provide a MWE, please?

**Comment by bdtc** [comment] 2020-03-24 12:29
```

\documentclass{article}

\usepackage{polyglossia}

\setdefaultlanguage{english}

\setotherlanguages{czech,greek}

\begin{document}

Hello, world.

\end{document}

```

**Comment by jspitz** [comment] 2020-03-24 14:00
And what is the error message you get? Please quote as much context as necessary from the log file.

**Comment by bdtc** [comment] 2020-03-25 01:28
```
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex 2020.3.23)  24 MAR 2020 20:23
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**pg.tex
(./pg.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-03-06>

(... cut ...)

(/usr/local/texlive/2020/texmf-dist/tex/latex/polyglossia/gloss-czech.ldf
File: gloss-czech.ldf polyglossia: module for czech
The property list \polyglossia@langsetup contains the pairs (without outer
braces):

(... cut ...)

Package polyglossia Warning: No hyphenation patterns were loaded for `czech'
(polyglossia)                I will use \language=\l@nohyphenation instead on i
nput line 10.

! Undefined control sequence.
\adddialect ...####1####2####3####4{}\fi }\bbl@cs 
                                                  {languages}\endgroup 
l.10 }
      
? x


```

So this error occurs while compiling polyglossia/gloss-czech.ldf.

**Comment by jspitz** [comment] 2020-03-25 05:58
Uhm. I don't have TL 2020 prerelase installed yet, but I don't get this error with TL 19 even if I remove czech hyphenation patterns. Looks like a bug in TL 2020.

**Comment by bdtc** [comment] 2020-03-25 06:03
Yes, babel had a big update a few days ago.

**Comment by jspitz** [comment] 2020-03-25 06:13
I cannot imagine how a babel update could have an impact on polyglossia.

**Comment by bdtc** [comment] 2020-03-25 08:26
It looks like polyglossia imports things from babel, as seen in polyglossia's babelsh.def file.  This is probably related to [Issue 399](https://github.com/reutenauer/polyglossia/issues/399), with a similar error.

**Comment by reutenauer** [comment] 2020-03-25 08:47
Polyglossia is only “importing” from Babel in the sense that we can, very occasionally, copy some code manually.  It’s not affected by Babel updates in distributions.

**Comment by bdtc** [comment] 2020-03-25 09:47
Whatever it is, it's very subtle.

Running the latest updated TL2019 it works.

Running TL2020 pretest it fails, even though the version of polyglossia is the same in each.

I tried copying every .sty which gets used for this document from 2019 into the local directory, in case a change in some other package caused the issue, as well as some polyglossia .ldf and .def files from 2019, and it still fails even though almost everything is being taken from 2019.

All of this almost points to some recent change in xelatex, but it also fails with lualatex.

And the error message is calling for a macro name \bbl@cs which doesn't seem to exist in the entire polyglossia directory.

Hopefully this can be found before the TL freeze in a few days.

**Comment by reutenauer** [comment] 2020-03-25 10:36
> Hopefully this can be found before the TL freeze in a few days.

  I’d like to, but it doesn’t seem likely if the issue is as complex
as you make it sound.

**Comment by reutenauer** [comment] 2020-03-25 10:55
@bdtc Can you try adding

    \makeatletter
    \def\bbl@cs#1{\csname bbl@#1\endcsname}
    \makeatother

in the preamble of your document?

**Comment by wehro** [comment] 2020-03-25 11:48
> I cannot imagine how a babel update could have an impact on polyglossia.

As far as I know, the babel files `hyphen.cfg` and `switch.def` are dumped into the format files. So we can never be sure.

**Comment by reutenauer** [comment] 2020-03-25 11:59
> As far as I know, the babel files `hyphen.cfg` and `switch.def` are dumped into the format files. So we can never be sure.

  Yes, that’s precisely the problem here (via `switch.def`).  That’s an
abnormal situation, and I’ve tried to point it out Javier years ago,
without success so far.

**Comment by bdtc** [comment] 2020-03-25 12:07
Your definition of bbl@cs immediately after loading polyglossia fixes the problem.

This appeared because I have a bunch of test files for the Lwarp package, including a trivial one for polyglossia.  This time of year with the TeXLive rush is always "interersting".

**Comment by reutenauer** [comment] 2020-03-25 12:23
> Your definition of bbl@cs immediately after loading polyglossia fixes the problem.

  Great, thanks for testing!  I added that definition to Polyglossia, it will be part of today’s update.

> This appeared because I have a bunch of test files for the Lwarp package, including a trivial one for polyglossia.  This time of year with the TeXLive rush is always "interersting".

  That’s one way to put it ...

**Closed** 2020-03-25 14:26 UTC

**Comment by moewew** [comment] 2020-03-25 16:32
Since this just appears to be a small oversight in `switch.def`/`babel` I opened an issue at https://github.com/latex3/babel/issues/57. (This has happened before and was quickly fixed back then: https://github.com/latex3/latex2e/issues/17.)

**Comment by reutenauer** [comment] 2020-03-25 17:26
Thanks Moritz, but in the long run that’s not a solution.  We can’t keep on firefightinging problems that could easily be avoided.
