### ISSUE TITLE
Slash is rendered as division slash U+2215 for Roboto Mono

### ISSUE THREAD

**Issue by misho104** [reutenauer/polyglossia#625] opened 2024-02-04 09:13 UTC
Hi. Using [Roboto Mono](https://fonts.google.com/specimen/Roboto+Mono) with Polyglossia causes an issue: the code

```latex
\documentclass{article}
\usepackage{polyglossia}
\newfontfamily{\englishfont}{Roboto Mono}
\setdefaultlanguage{english}
\begin{document}
/////
\end{document}
```
compiled by LuaLaTeX generates a PDF file with [Division Slash U+2215](https://www.compart.com/en/unicode/U+2215), not the ASCII slashes.

This is likely caused because Roboto Mono does not have a glyph for U+002F but its U+002F is redirected to U+2215.

<a href="https://github.com/reutenauer/polyglossia/assets/776101/a5800fe2-7a2d-40be-a302-6990717c3785"><img width="123" alt="screen" src="https://github.com/reutenauer/polyglossia/assets/776101/a5800fe2-7a2d-40be-a302-6990717c3785"></a>

Interestingly, the issue does not occur in the following code:
```latex
%% fontfamily defined before loading PolyGlossia
\documentclass{article}
\usepackage{fontspec}
\newfontfamily{\englishfont}{Roboto Mono}
\usepackage{polyglossia}
\setdefaultlanguage{english}
\begin{document}
/////
\end{document}

% This code also works fine.
%\documentclass{article}
%\usepackage{fontspec}
%\setmainfont{Roboto Mono}
%\begin{document}
%/////
%\end{document}
```

**Comment by jspitz** [comment] 2024-02-04 09:39
Cannot reproduce; here the following code:
```tex
% !TeX TS-program = lualatex
\documentclass{article}
\usepackage{polyglossia}
\newfontfamily{\englishfont}{Roboto Mono}
\setdefaultlanguage{english}
\begin{document}
	/////
\end{document}
```
produces:
![grafik](https://github.com/reutenauer/polyglossia/assets/4538783/dd1e435d-8599-4b63-9e9d-778d762c6986)

What happens if you select another luatexrenderer for polyglossia (or Renderer for the font itself), e.g.
```tex
\newfontfamily\englishfont{Roboto Mono}[Renderer=Base]
```

**Comment by misho104** [comment] 2024-02-04 11:28
Thanks for the clarification! `Renderer=Base` and `Node` produce slash (U+2F), while `HarfBuzz` produces U+2215.

It seems an issue of my HarfBuzz (I have `HarfBuzz 8.3.0` via Homebrew, but LuaLaTeX may be using another installation).

**Comment by jspitz** [comment] 2024-02-04 12:04
OK, so we can close this ticket.

**Closed** 2024-02-04 12:05 UTC
