### ISSUE TITLE
Command \pghyphenation is not recognized

### ISSUE THREAD

**Issue by ArsaiGit** [reutenauer/polyglossia#665] opened 2024-10-14 17:22 UTC
### Issue
The command `\pghyphenation` is not recognized, leading to a "_Undefined control sequence_" error from LaTeX upon compilation.

### Installation
- MikTeX with the newest updates as per 14th of october 2024
- Specified installation contains `polyglossia` version 2.2
- Compiled with LuaLaTeX

### MWE for reproduction
```latex
\documentclass{scrarticle}

\usepackage{polyglossia}
\setdefaultlanguage{english}
\pghyphenation{english}{te-st}

\begin{document}
	
	This is a test.
	
\end{document}
```
Additional Notes:
- it does not matter whether standard classes or KOMA-classes are used
- the language does not seem to matter (only tested english and german with identical results)

### Screenshot 
![grafik](https://github.com/user-attachments/assets/88cd4d18-78d9-4dea-aebb-4085f1932e1c)

**Comment by jspitz** [comment] 2024-10-14 17:28
I assume this is a duplicate of #654
The bug is fixed in the recent version.

**Closed by jspitz** 2024-10-14 17:28 UTC

**Comment by ArsaiGit** [comment] 2024-10-14 17:36
Thanks for the quick reply. Confirmed to be a duplicate since the quickfix/workaround works.

If I may ask, is there a reason why recent versions are not accessible via MikTeX ? Or is this an issue on the side of the distribution database?

**Comment by jspitz** [comment] 2024-10-14 17:37
> If I may ask, is there a reason why recent versions are not accessible via MikTeX ? Or is this an issue on the side of the distribution database?

I cannot answer that. You have to ask MikTeX.

**Comment by ArsaiGit** [comment] 2024-10-14 17:41
Alright, thank you very much. Maybe the update is still just too recent.
