### ISSUE TITLE
French punctuation spacing

### ISSUE THREAD

**Issue by wehro** [reutenauer/polyglossia#345] opened 2019-11-03 19:59 UTC
Before `;`, `!`, and `?`, babel-french inserts half an interword space (`0.5\fontdimen2\font`). Polyglossia uses a thin space instead, which is defined as a sixth of a quad (`0.16667em`). This is obviously not the same, but the difference is imperceptible in most cases, as an interword space is typically about a third of a quad or slightly less.
However, for fonts with unusual values of the interword space, the difference becomes obvious, e.g. for *TeX Gyre Chorus* (aka *Zapf Chancery*). For a 12 point font size, the interword space is 2.6 pt approximately for this font. The babel spacing looks like this:
![Spationierung_babel](https://user-images.githubusercontent.com/33468411/68090855-35e1d000-fe79-11e9-87c9-f4994522ac3d.png)
Note the slightly larger spaces with polyglossia:
![Spationierung_polyglossia](https://user-images.githubusercontent.com/33468411/68090870-527e0800-fe79-11e9-8b09-6bbc18d1559f.png)

For the colon, the results are not even consistent within polyglossia. XeTeX inserts an interword space (stretchable and shrinkable), just as babel does, but LuaTeX a “thick space”, corresponding to `\;` in math mode (`0.2777em`). For most fonts, the “thick space” is slightly smaller than an interword space, but for *TeX Gyre Chorus*, it is larger. This means that the space before the colon is larger than the space thereafter, which is rather odd.
Compare the LuaTeX results for *Latin Modern* (12 pt):
![Latin-modern](https://user-images.githubusercontent.com/33468411/68091045-5ad74280-fe7b-11e9-9ebe-a5d7239bcaae.png)
And for *TeX Gyre Chorus* (12 pt):
![TeX-Gyre-Chorus](https://user-images.githubusercontent.com/33468411/68091059-76dae400-fe7b-11e9-9cf8-e5f16e7ff81e.png)

I think the example of *TeX Gyre Chorus* shows that the babel approach is superior and we should implement punctuation spacing like this also in polyglossia.

Furthermore, babel-french offers a `ThinColonSpace` option, allowing to space colons the same way as other punctuation marks, which should be provided also by polyglossia.

**Comment by wehro** [comment] 2019-11-06 12:46
So far, the option `autospaceguillemets=false` does not work with LuaTeX.

**Comment by jspitz** [comment] 2019-11-06 14:38
are you planning to work on this, @wehro?

**Comment by wehro** [comment] 2019-11-06 16:06
> are you planning to work on this, @wehro?

Yes, I will try.

**Comment by jspitz** [comment] 2019-11-08 15:56
@wehro please close this ticket when the issue is fixed.

**Comment by wehro** [comment] 2019-11-09 11:47
With XeTeX, it is not possible to turn the `autospaceguillemets` option off. It only works with LuaTeX so far.
```
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{french}

\begin{document}
«abc»

\begin{french}[autospaceguillemets=false]
«abc»
\end{french}
\end{document}
```

**Comment by wehro** [comment] 2019-11-09 12:08
> With XeTeX, it is not possible to turn the `autospaceguillemets` option off.

I have no idea why. Can someone have a look, please.

**Comment by reutenauer** [comment] 2019-11-09 13:09
I can have a look some time next week.

**Closed** 2019-11-09 15:20 UTC

**Comment by jspitz** [comment] 2019-11-09 15:22
> With XeTeX, it is not possible to turn the `autospaceguillemets` option off. It only works with LuaTeX so far.

The issue here was that the XeTeXcharclass remains active within the nested French, so the interchartokens are inserted. Fixed by adapting the space macro.
