### ISSUE TITLE
font style specification inside \textenglish{} resets language

### ISSUE THREAD

**Issue by itaisha** [reutenauer/polyglossia#53] opened 2013-07-15 07:50 UTC
write a document in a non-english language, preferably one that isn't latin. select a different font for english.
write a line of english text, and set some of the text to Sans Serif or Typewriter - 

\textenglish{Hello \textsf{World}}

desired outcome - the text should compile with the appropriate font family.
actual outcome - the text inside \textsf{} is rendered with the main font, and not the english font.

using \textsf{\textenglish{}}, i.e. - the family spec. first, works correctly, but sometimes you would want a line of English text with only a few words in a different font family.

the same applies for \textrm and \texttt

**Comment by jspitz** [comment] 2019-08-23 19:17
Cannot reproduce with current master. MWE
```
% !TEX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}

\setmainlanguage{arabic}
\setotherlanguage{english}

% neither with this:
%\newfontfamily\arabicfont[Script=Arabic]{Scheherazade}
%\setmainfont{Linux Libertine O}

% nor this:
\setmainfont{Scheherazade}[Script=Arabic]
\newfontfamily{\englishfont}{Linux Libertine O}


\begin{document}

مرحبا بالعالم

\textenglish{Hello \textsf{World}}

\end{document}
```

I can with the released version. So this is apparently fixed.

**Comment by jspitz** [comment] 2019-08-24 08:28
Someone who can please close this ticket.

**Closed** 2019-08-24 08:28 UTC
