### ISSUE TITLE
Wrong spacing of swiss-german quotation marks if main language is french

### ISSUE THREAD

**Issue by adn792** [reutenauer/polyglossia#169] opened 2016-11-23 17:20 UTC
Hi, 

Apparently, when \setmainlanguage{french} is set in polyglossia, the macros \guillemotleft and  \guilsinglleft always print << or < _followed by some white space_, and the macros \guillemotright and \guilsinglright always print >> or > _preceded by some white space_ too.
In french, this is the normal behaviour.

However, if you try to cite some german (using the swiss-german quotation marks) text in your french text, the above described behaviour adds some spacing between the quotation marks and the quoted words, although this shouldn't be the case according to the swiss-german practices ([see for instance here](https://de.wikipedia.org/wiki/Anf%C3%BChrungszeichen#Schweiz.2C_Liechtenstein.2C_Frankreich)).

This is also problematic when using polyglossia with the csquotes package, which uses \guillemotleft, \guilsinglleft, \guillemotright and \guilsinglright to define its swiss-german quote style (see [csquotes.def](https://mirror.hmc.edu/ctan/macros/latex/contrib/csquotes/csquotes.def), lines 121 sqq).

So: the french spacing after and before \guillemotleft, \guilsinglleft, \guillemotright and \guilsinglright should only appear when the actual language in a portion of text is french, and not when these macros are used when any other language is selected.

Thanks and best regards
Adrien

% Minimal working example below

\documentclass{minimal}
\usepackage{polyglossia}
\setmainlanguage{french}% comment this line to see the correct output in swiss-german style.
\setotherlanguage[variant=swiss]{german}
\begin{document}
The output is correct here (opening guillemots/chevrons are followed by proper spacing; closing guillemots/chevrons are preceded by proper spacing):

\guillemotleft Un peu de \guilsinglleft texte\guilsinglright{} en français.\guillemotright

The output is wrong here (in swiss-german, opening guillemots/chevrons shouldn't be followed by any spacing, neither closing guillemots/chevrons should be preceded by any spacing):

\foreignlanguage{german}{\guillemotleft Ein bisschen \guilsinglleft Text\guilsinglright{} auf Deutsch.\guillemotright}
\end{document}

**Comment by jspitz** [comment] 2016-12-13 17:50
Seems related to https://github.com/reutenauer/polyglossia/issues/68

**Comment by jspitz** [comment] 2019-08-20 08:11
The cause is the same as for #233: `\french@punctuation` remains in effect if another language is nested into french (as main language or secondary language).

Probably the only solution is to define `\nofrench@punctuation` in the style file and issue it at the very beginning of any language switch. But then, other languages might have similar hooks that need to be taken care of.

**Comment by bastien-roucaries** [comment] 2019-08-20 08:29
Could you retest with githead ?

Normally this is fixed

**Comment by jspitz** [comment] 2019-08-20 08:52
It's not fixed in head. It's only fixed if french is a secondary language (and hence closed before the other language sets in).

**Comment by jspitz** [comment] 2019-08-20 08:54
See #66 for a (incomlete) idea.

**Comment by reutenauer** [comment] 2019-08-22 09:16
Fixed by #235.

**Closed** 2019-08-22 09:18 UTC
