### ISSUE TITLE
setdefaultlanguage error for some languages: ldf:180: LaTeX Error: Missing \begin{document} german

### ISSUE THREAD

**Issue by dflvunoooooo** [reutenauer/polyglossia#628] opened 2024-02-16 18:25 UTC
Since the update today, I can no longer compile my document. If I specify the language with `\setdefaultlanguage{german}`, I get the error `/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-german.ldf:180: LaTeX Error: Missing \begin{document}.`. If I use danish, it is working. 

```
\documentclass{scrartcl} 

\usepackage{polyglossia}
\setdefaultlanguage{german}

\begin{document}
Bla bla bla.
\end{document}
```

The full log:
```
This is LuaHBTeX, Version 1.17.0 (TeX Live 2023) 
 system commands enabled.
("/home/brian/Daten/Latex/_Problem/robExt polyglossia language/test.tex"
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-13>
 (/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrartcl.cls
Document Class: scrartcl 2023/07/07 v3.41 KOMA-Script document class (article)
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrkbase.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrbase.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrlfile.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrlfile-hook.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrlogo.sty)))
(/usr/local/texlive/2023/texmf-dist/tex/latex/graphics/keyval.sty)))
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/tocbasic.sty)
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/scrsize11pt.clo)
(/usr/local/texlive/2023/texmf-dist/tex/latex/koma-script/typearea.sty))
(/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/polyglossia.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2023/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2023/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2023/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
(/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)))
 (/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/local/texlive/2023/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2023/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/local/texlive/2023/texmf-dist/tex/luatex/ctablestack/ctablestack.sty))
(/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-latex.lde))
(/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/gloss-german.ldf
! Use of \__prop_put_linked:wnnN doesn't match its definition.
<recently read> \xpg@alias@keyvals@german@1996 
                               
l.180 ...t@alias@values{german}{spelling}{new}{1996}
                                                  

! LaTeX Error: Missing \begin{document}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.180 ...t@alias@values{german}{spelling}{new}{1996}
                                                  
(/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/babelsh.def))
(./test.aux) (/usr/local/texlive/2023/texmf-dist/tex/latex/base/ts1cmr.fd)
[1{/usr/local/texlive/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
(./test.aux))
(see the transcript file for additional information)
 426 words of node memory still in use:
   3 hlist, 1 vlist, 1 rule, 2 glue, 3 kern, 1 glyph, 4 attribute, 52 glue_spec
, 4 attribute_list, 1 write nodes
   avail lists: 1:1,2:66,3:20,4:1,5:28,6:4,7:190,9:28,11:18
</usr/local/texlive/2023/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.
otf>
Output written on test.pdf (1 page, 4888 bytes).
Transcript written on test.log.

```
Don't know if it is related to #627 ?

**Comment by jspitz** [comment] 2024-02-16 19:50
This is a duplicate of #626

**Closed by jspitz** 2024-02-16 19:50 UTC
