### ISSUE TITLE
problem with hebrew and \verb

### ISSUE THREAD

**Issue by idoh** [reutenauer/polyglossia#74] opened 2014-05-13 21:15 UTC
There is a problem with hebrew and \verb. See the following MWE:

\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[numerals=arabic]{hebrew}
\setotherlanguage{english}
\newfontfamily\hebrewfont{Frank Ruehl CLM}
\begin{document}
שלום.
\verb|Hello|
\end{document}

I used the workaround suggested in:

http://tex.stackexchange.com/questions/39262/polyglossia-and-minted-the-current-roman-font-does-not-contain-the-hebrew-scri

and it worked. Yet, that should be fixed.

Ido

**Comment by scottkosty** [comment] 2018-09-23 15:56
This issue still seems to be relevant. The same workaround worked [https://www.lyx.org/trac/ticket/11299](here).

@reutenauer Do you think that is indeed the same issue as here? Would it help to have another test case from that example? I can try to reduce it to a minimal example .tex file and post it here, if that would help.

**Comment by jspitz** [comment] 2019-08-23 14:02
The issue is fixed in current master.

Someone who can please close this ticket.

**Closed** 2019-08-23 18:01 UTC
