### ISSUE TITLE
urdu module: changes sought

### ISSUE THREAD

**Issue by KamalAbdali** [reutenauer/polyglossia#206] opened 2018-07-14 15:30 UTC
In the Polyglossia module for urdu that I had contributed, I want to make some changes, especially in \def\captionsurdu. Before submitting a revision, I want to try out the changes. In fact I would like to try a few changes in some other modules too. Is there a simple way to do the tests by adding local definitions for Polyglossia in the tex program preamble?  I assume one could add a file to localtexmf and do mktexlsr to make a completely new local tex, but is it possible to avoid that.

**Comment by jspitz** [comment] 2019-08-28 04:34
You can add local definitions by 
```
\AtBeginDocument{%
\appto\captionsurdu{...}
}
```
in the preamble. To change and test the module, I would rather suggest to put a copy to your HOMETEXMF tree.

**Comment by jspitz** [comment] 2019-08-28 04:34
This is actually not a bug or feature request. Closing.

**Closed by jspitz** 2019-08-28 04:34 UTC
