### ISSUE TITLE
Incorrect minus position for negative nembers in RTL context

### ISSUE THREAD

**Issue by seloumi** [reutenauer/polyglossia#590] opened 2023-05-15 21:11 UTC
With the recent version of  polyglossia minus sign is reversed It appears to the right of the number when  It should appear on the left

```latex
\documentclass{article}
\usepackage{polyglossia}

\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}
\Huge
-1
\end{document}

```

**Comment by jspitz** [comment] 2023-05-16 06:33
Do you mean to imply ("with the recent version") that this worked in previous versions of `polyglossia`? If so, can you remember which version?

**Comment by seloumi** [comment] 2023-05-16 06:54
I'm not sure, I think the problem appeared with the last version or the one before it

**Comment by jspitz** [comment] 2023-05-16 07:19
I now tried back to version 1.42 (Oct 2018), and still the same. Are you sure this is not due to another package update (e.g., `bidi`)? I really doubt this is something we handle in `polyglossia`.

**Comment by seloumi** [comment] 2023-05-16 13:16
You're right, I didn't pay attention  to that, sorry

**Comment by Udi-Fogiel** [comment] 2023-06-03 01:25
It think polyglossia does somehow does changes the behavior. Compare the following (I intentionally did not load the font with the Arabic script)

```TeX
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{arabic}
\newfontfamily\arabicfont[Mapping=tex-text]{Amiri}

\begin{document}
	-1
	
	\beginL\expandafter\meaning\the\font
\end{document}
``` 

which produce

![image](https://github.com/reutenauer/polyglossia/assets/110533647/6b368638-8dd9-47c3-b68f-0475228e0950)

while

```
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{fontspec}
\usepackage[RTLdocument]{bidi}
\setmainfont{Amiri}

\begin{document}
	-1
	
	\beginL\expandafter\meaning\the\font
\end{document}
```

produce

![image](https://github.com/reutenauer/polyglossia/assets/110533647/cd4892b5-05d6-421a-aa81-331e38160cdc)

**Comment by Udi-Fogiel** [comment] 2023-06-03 01:46
Just to make things clear, I think the hyphen should be on the right, as this is not a minus sign... (and with the Arabic script it also appears on the right with plain `bidi`), but it does look like polyglossia is doing something. FWIW I could not reproduce the same with Hebrew.

**Comment by Udi-Fogiel** [comment] 2023-06-03 02:00
Ok, this is clear now. `bidi` inserts `\if@nonlatin\char"200F`, where `\char"200F` is a RTL mark (0x200f) between numbers, Arabic numerals and number separators ( - .), via `\XeTeXinterchartoks`.  Weather it should do it is debatable. 

`gloss-hebrew.ldf` and `gloss-uyghur.ldf` "fix" it, this is why I could not reproduce with Hebrew. The "fix" in these files are debatable as well, as giving a correct script changes the behavior, so what is the correct one?

**Comment by Udi-Fogiel** [comment] 2023-06-03 03:02
This is my two cents on this topic. I think `bidi` is trying to mimic the affect of a font with a RTL script on the Unicode bidi algorithm XeTeX applies (at least partially), even when a script is not given explicitly, and when the conditional `\if@nonlatin` (which actually `polyglossia` sets, and not `bidi`), is true.

The comments in `gloss-hebrew.ldf` (line 125 specifically) suggested this is wrong for hebrew, but consider the following two files

```TeX
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{hebrew}
\newfontfamily\hebrewfont{David CLM}

\begin{document}
	שלום -12 
\end{document}
```   
![image](https://github.com/reutenauer/polyglossia/assets/110533647/9eba1680-8c40-4688-ad04-fa2dc2568daa)
```Tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage{hebrew}
\newfontfamily\hebrewfont[Script=Hebrew]{David CLM}

\begin{document}
	שלום -12
\end{document}
```
![image](https://github.com/reutenauer/polyglossia/assets/110533647/9cf878be-b710-4edd-874b-a325e8c33493)

If I remove the "fix" from `gloss-hebrew.ldf`, both codes produce the second result.

**Comment by jspitz** [comment] 2023-06-03 09:39
The Hebrew fix has been done per user request to fix #441.

**Comment by Udi-Fogiel** [comment] 2023-06-03 10:29
I'm sorry, but I don't really understand how this is a fix for what is described in #441. I think the real source of the problem is using fonts with wrong Script tags. 

In the following examples I will use `\newfontfamily\hebrewfont` instead of `\setmainfont` beacuse `polyglossia` adds the Script tag automatically in the latter case (maybe that what changed in 2020 that fixed the code in the examples given in #441).

with default settings of `polyglossia`
```TeX
\documentclass[12pt]{article}

\usepackage{polyglossia}
\setdefaultlanguage{hebrew}	
\newfontfamily\hebrewfont[Mapping=tex-text]{Times New Roman}

\begin{document}
% wrong: misplaced bracket:
[א 1-2]

% good: bracket in place:
[א 1 2]
\end{document}
```
![image](https://github.com/reutenauer/polyglossia/assets/110533647/ee68f9e0-addf-4c5c-8210-de697c07f68e)

This is what I get from the same code after removing the fix for #441
![image](https://github.com/reutenauer/polyglossia/assets/110533647/5ee23150-8ad2-45d6-8b0a-b2259e3f2c7e)

And this is with the same code but adding `Script=Hebrew` to the font
![image](https://github.com/reutenauer/polyglossia/assets/110533647/bd44316d-fabc-4497-b71a-1a913c7d61d9)


with default settings of `polyglossia`
```TeX
\documentclass[12pt]{article}

\usepackage{polyglossia}
\setdefaultlanguage{hebrew}	
\newfontfamily\hebrewfont[Mapping=tex-text]{Times New Roman}

\begin{document}
	% wrong: misplaced full-stop:
	עמוד 1-2.
	
	% good: full-stop in place:
	עמוד 1 2.
\end{document}
```
![image](https://github.com/reutenauer/polyglossia/assets/110533647/83452f8e-13ef-45bc-a552-d6a4f7526ebe)

This is what I get from the same code after removing the fix for #441
![image](https://github.com/reutenauer/polyglossia/assets/110533647/8dac4924-9d1c-4b88-9c9b-f81d30364319)

And this is with the same code but adding `Script=Hebrew` to the font
![image](https://github.com/reutenauer/polyglossia/assets/110533647/33431dca-2859-4953-b503-06ae0ea59c87)

As you can see, what `bidi` was trying to do is to get a closer result the the correct one, but it not always works. Without `bidi`'s patch, things are even further from the correct result.

**Comment by Udi-Fogiel** [comment] 2023-06-03 10:50
Tested with plain xetex, got the same results, e.g., got the first results with no patching from bidi, or hebrew script, the second with the patching of bidi, and the third with loading the font with the hebrew script.

**Comment by jspitz** [comment] 2023-06-03 12:31
If you can prepare a PR of what you think is correct Hebrew behavior, I can merge that. I just want to prevent some ping-pong game of changing behavior.

**Comment by jspitz** [comment] 2023-06-04 11:03
Why did you reopen this? We are only discussing the Hebrew exception to the fix here, not Arabic (the topic of this ticket).

**Closed by jspitz** 2023-06-04 11:03 UTC

**Comment by Udi-Fogiel** [comment] 2023-06-04 13:06
After trying some more examples, it seems that in some cases the way bidi patches things is desired, and in some cases it makes things worse. It looks like the author of bidi is inactive (at least there was no movement in the repository, nor he responded to a PR I've made), so I can't really tell the reason behind this patch. 

Using the correct script fix things with and without bidi's patch, so in the end I don't have a strong opinion about keeping the patch, or not. 

But, if it will be decided to prevent bidi's patch for Hebrew, maybe a few changes in the code would be good. For example, shouldn't the test in 

```TeX
\def\nohebrew@ltr@numbers{%
    \ifxetex
      % Restore bidi's \DigitsDotDashInterCharToks
      \let\DigitsDotDashInterCharToks\xpg@orig@DigitsDotDashInterCharToks%
    \fi%
}
```
be made outside the definition of the macro?   there is no need to test the engine each time the macro is evoked. 

I'm also wondering if the best way to disable bidi's patch is with `\renewcommand*{\DigitsDotDashInterCharToks}{}`. Do you happen to know if `\XeTeXcharclass` expands the macros before inserting them to the horizontal list? can it interfere with spacing, hyphenation, kerning or anything else? 

Maybe restoring all characters to character class 0 is better, e.g.,

```TeX
\bidi@digits=`\0 \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\9 \advance\bidi@digits \@ne \repeat
\bidi@digits=`\٠ \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\٩ \advance\bidi@digits \@ne \repeat
\bidi@digits=`\۰ \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\۹ \advance\bidi@digits \@ne \repeat
```

Do you have any thoughts about it?

**Comment by jspitz** [comment] 2023-06-04 13:38
> But, if it will be decided to prevent bidi's patch for Hebrew, maybe a few changes in the code would be good. For example, shouldn't the test in
> 
> ```
> \def\nohebrew@ltr@numbers{%
>     \ifxetex
>       % Restore bidi's \DigitsDotDashInterCharToks
>       \let\DigitsDotDashInterCharToks\xpg@orig@DigitsDotDashInterCharToks%
>     \fi%
> }
> ```
> 
> be made outside the definition of the macro? there is no need to test the engine each time the macro is evoked.

But then the macro is undefined with LuaTeX, and we'll get an error. Or did I misunderstand your proposal?

> I'm also wondering if the best way to disable bidi's patch is with `\renewcommand*{\DigitsDotDashInterCharToks}{}`. Do you happen to know if `\XeTeXcharclass` expands the macros before inserting them to the horizontal list? can it interfere with spacing, hyphenation, kerning or anything else?

Not to my knowledge.

> Maybe restoring all characters to character class 0 is better, e.g.,
> 
> ```
> \bidi@digits=`\0 \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\9 \advance\bidi@digits \@ne \repeat
> \bidi@digits=`\٠ \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\٩ \advance\bidi@digits \@ne \repeat
> \bidi@digits=`\۰ \loop \XeTeXcharclass \bidi@digits 0 \ifnum\bidi@digits<`\۹ \advance\bidi@digits \@ne \repeat
> ```
> 
> Do you have any thoughts about it?

Given the issue does not occur if the script is correctly set, I am actually leaning towards removing the `hebrew@ltr@numbers` workaround altogether.

**Comment by Udi-Fogiel** [comment] 2023-06-04 13:51
Never mind... just compared a large document without removing what bidi does and it seems it does harm in some cases...

>But then the macro is undefined with LuaTeX, and we'll get an error. Or did I misunderstand your proposal?

I'm suggesting to change it to something like

```TeX
\newcommand*\def\nohebrew@ltr@numbers{}
\ifxetex
\def\nohebrew@ltr@numbers{%
      % Restore bidi's \DigitsDotDashInterCharToks
      \let\DigitsDotDashInterCharToks\xpg@orig@DigitsDotDashInterCharToks
}
\fi
```

**Comment by jspitz** [comment] 2023-06-04 14:13
Sure. I don't think the test is really expensive, though.

**Comment by jspitz** [comment] 2023-06-04 14:20
Nonetheless done at 1dad132f4c98
