### ISSUE TITLE
French punctuation spacing persists after ending the language environment

### ISSUE THREAD

**Issue by svenper** [reutenauer/polyglossia#201] opened 2018-03-15 22:14 UTC
I am not sure if this is could be a `fontspec` issue, but an educated guess with `otfinfo` tells us that there is no French `locl` features that could linger.

```
otfinfo --scripts $(locate -i sourcecodepro-regular.otf)
DFLT		Default
cyrl		Cyrillic
cyrl.SRB	Cyrillic/Serbian
grek		Greek
latn		Latin
latn.NSM	Latin/Northern Sami
latn.SKS	Latin/Skolt Sami
```

```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Source Code Pro}
\usepackage{polyglossia}
\setmainlanguage{english}
\setotherlanguage{french}
\def\somepunct{a! b? c; d: e! \languagename\hfill}
\begin{document}

{\begin{english}\somepunct\end{english}}

{\begin{french}\somepunct\end{french}}

{\begin{english}\somepunct\end{english}}

\end{document}
```

![1](https://user-images.githubusercontent.com/15199675/37493601-c649f894-28a5-11e8-895c-8abf980e48a7.png)

**Comment by eg9** [comment] 2018-03-15 22:37
@svenper 

I cannot reproduce it.

<img width="321" alt="screen shot 2018-03-15 at 23 36 45" src="https://user-images.githubusercontent.com/302839/37494589-c11fc71e-28a9-11e8-8495-fcdf39111ff0.png">

**Comment by svenper** [comment] 2018-03-16 01:42
That's odd. I tried with `xelatex` instead of the usual `lualatex` and it worked as expected. Is this really a problem with LuaLaTeX then?

**Comment by reutenauer** [comment] 2018-03-16 02:45
Most likely with the Polyglossia code for LuaTeX.  Thanks for the report, I’ll try to have a look.

**Comment by svenper** [comment] 2018-12-29 22:41
`automaticspacesaroundguillemets=false` seems like it should disable this, but it does not, either for XeTeX or LuaTeX. Only Lua currently does not reset it for other languages, however.

For anyone with the same problem, a temporary workaround that completely disables french punctuation spacing (put after first loading the language):

```tex
\makeatletter
\def\noextras@french{}
\def\blockextras@french{}
\def\inlineextras@french{}
\makeatother
```

**Comment by adunning** [comment] 2019-01-01 23:39
This is a duplicate of #49, #66, #68, #153, and #182

**Closed** 2019-08-16 10:27 UTC
