### ISSUE TITLE
Period goes before number when a number ends a sentence while using polyglossia

### ISSUE THREAD

**Issue by xpas2r** [reutenauer/polyglossia#155] opened 2016-08-18 06:58 UTC
After update of May 2016 using 'polyglossia' and writing numbers result in misplaced dots. Maybe a 'bidi'-bug?

**Comment by reutenauer** [comment] 2016-08-18 13:01
Sorry, I really need a concrete example in order to be able to give any help.

**Comment by xpas2r** [comment] 2016-08-18 13:57
Thank you for your prompt answer.

Here is a xelatex-source file:

    \documentclass{article}

    \usepackage{xltxtra}

    \defaultfontfeatures{Mapping=tex-text}

    \setmainfont{Linux Libertine O}

    \usepackage{polyglossia}

    \setdefaultlanguage{danish}

    \usepackage{bidi}

    \begin{document}

    This is an example 2016.08.17

    Which is meant to be read: yyyy.mm.dd but in outprint(pdf) is reversed.

    \end{document}

I have the latest tex-live version with an update of today.

I have attached the pdf-out-put-file.

Bent J.

Den 18-08-2016 kl. 15:01 skrev Arthur Reutenauer:

**Comment by reutenauer** [comment] 2016-08-18 14:50
Yes, this behaviour comes from `bidi`, there is nothing Polyglossia can do here.

**Comment by vafa** [comment] 2016-09-13 08:11
This is a polyglossia bug, period.

**Comment by eg9** [comment] 2016-09-16 09:57
@vafa  As it is evident from today's update of `bidi` to version 20.0, your claim was wrong.

**Comment by eg9** [comment] 2016-09-16 09:59
@xpas2r Try updating `bidi` to version 20.0; the issue should have been removed.

**Comment by vafa** [comment] 2016-09-17 04:22
@eg9 

> As it is evident from today's update of bidi to version 20.0, your claim was wrong.

Is it a habit of yours to say nonsense? or are you a liar like @reutenauer . Stop going around and say garbage!

Having said that, he `bidi` package update has nothing to do with this. I never even intended to do anything about `polyglossia`. I simply implemented a `captionscript` key for `listings` package and to make things consistent, I changed `\if@Latin` Boolean to `\if@nonlatin`. `Polyglossia` still has the bug.

**Comment by eg9** [comment] 2016-09-17 10:28
@vafa 

I try to say sensible things (maybe sometimes I fail), but certainly don't go around insulting people.

The change from `\if@Latin` to `\if@nonlatin` is a *clear* attempt at fixing the things *you* broke.

Best regards.

**Comment by vafa** [comment] 2016-09-18 05:36
@eg9 

Here is a minimal example proving your claim:

```latex
\documentclass[a4paper, twoside, titlepage, 11pt]{report}
\usepackage{amsmath}
\usepackage{amsthm}
\usepackage{polyglossia}

\setmainlanguage{hebrew}
\setotherlanguage{english}
\newfontfamily\hebrewfont[Script=Hebrew]{Arial}

\begin{document}

\begin{equation}
1+2=3
\end{equation}

\end{document}
```
pay attention to the equation number. of course, this is one of other bugs of polyglossia.

**Comment by reutenauer** [comment] 2016-09-18 20:40
@vafa, this is really not helpful.  @xpas2r, can you confirm that upgrading to `bidi` version 20.0 fixes the issue?

And thanks to @eg9 as usual.

**Comment by xpas2r** [comment] 2016-09-21 07:58
@reutenaur, sorry being absent for some days
yes the issue is solved but the solution(?) have given some new warnings in xelatex:

- latex-xetex-bidi.def 118
 LaTeX Error: Command \XeTeX already defined.
            Or name \end... illegal, see p.192 of the manual.
 
 See the LaTeX manual or LaTeX Companion for explanation.
 Type  H <return>  for immediate help.
  ...                                              
                                                   
- l.118 ...di@reflect@box{E}}\kern-.1667em \TeX}}$}}
 
 latex-xetex-bidi.def 120
 LaTeX Error: Command \XeLaTeX already defined.
                Or name \end... illegal, see p.192 of the manual.
 
 See the LaTeX manual or LaTeX Companion for explanation.
 Type  H <return>  for immediate help.
  ...                                              
                                                   
 l.120 ...@reflect@box{E}}\kern-.1667em \LaTeX}}$}}

I am not able to find clues in these warnings
I find it troublesome to pass the warnings during compilation.

**Comment by ExecutorElassus** [comment] 2017-02-10 12:40
@xpas2r these errors are from the file /usr/share/texmf-dist/tex/xelatex/bidi/latex-xetex-bidi.def, lines 122ff, which read as follows:

> \bidi@newrobustcmd*{\XeTeX}{\LR{\leavevmode$\smash{\hbox{X\lower.5ex
>   \hbox{\kern-.125em\bidi@reflect@box{E}}\kern-.1667em \TeX}}$}}
> \bidi@newrobustcmd*{\XeLaTeX}{\LR{\leavevmode$\smash{\hbox{X\lower.5ex
>   \hbox{\kern-.125em\bidi@reflect@box{E}}\kern-.1667em \LaTeX}}$}}
> \let\setRL=\setRTL
> \let\setLR=\setLTR
> \let\unsetRL=\setLTR
> \def\bidi@tabular@RTLcases{\let\@halignto\@empty\@bidi@tabular@RTLcases}
> \@ifpackageloaded{array}{%
> \def\@bidi@tabular@RTLcases{\@RTLtabtrue%
>   \leavevmode
>   \hbox \bgroup $\left.\col@sep\tabcolsep \let\d@llarbegin\begingroup
>                                     \let\d@llarend\endgroup
>   \@tabarray}
> \def\endbidi@tabular@RTLcases{\endarray \right\rbrace$\egroup}
> }

I'm getting the same error, and cannot compile my document. 

I don't know nearly enough about how to write these files to know how to fix this error, but it's causing the same problems on my system. To answer @eg9, I have bidi 20.9, installed today, so I'm not entirely sure what the source is, or how to fix it.

**Comment by jspitz** [comment] 2019-08-28 04:49
The issue is no more reproducable in current polyglossia.
The errors reported above are because xltxtra is loaded in the example, which does not work anymore. Updated example (which produces the correct output):

```
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{polyglossia}
\defaultfontfeatures{Mapping=tex-text}
\setmainfont{Linux Libertine O}
\setdefaultlanguage{danish}
\usepackage{bidi}

\begin{document}

This is an example 2016.08.17

Which is meant to be read: yyyy.mm.dd but in outprint(pdf) is reversed.

\end{document}
```

Note though that there was a bug in gloss-danish.ldf which prevents compilation with the released version (fixed in HEAD at https://github.com/reutenauer/polyglossia/commit/438006c51c8d00d7bf7be6956536f718ba6bbd04)

**Closed by jspitz** 2019-08-28 04:49 UTC
