### ISSUE TITLE
Polyglossia fails immediately with “Undefined control sequence

### ISSUE THREAD

**Issue by kaimikael** [reutenauer/polyglossia#627] opened 2024-02-16 15:52 UTC
This, very minimal, example:
```
\documentclass{article}
\usepackage{polyglossia}

\begin{document}
Foo
\end{document}
```

fails (in TeXShop 5.27) with the following output:
```
This is LuaHBTeX, Version 1.16.0 (TeX Live 2023) 
 restricted system commands enabled.
(./test.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2023-06-30>
 (/usr/local/texlive/2023/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/polyglossia.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/local/texlive/2023/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2023/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/local/texlive/2023/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/local/texlive/2023/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)))
 (/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec-luatex.sty
(/usr/local/texlive/2023/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/local/texlive/2023/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/local/texlive/2023/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/local/texlive/2023/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/local/texlive/2023/texmf-dist/tex/luatex/ctablestack/ctablestack.sty))
/usr/local/texlive/2023/texmf-dist/tex/latex/polyglossia/polyglossia.sty:973: U
ndefined control sequence.
l.973 \cs_new_nopar:Ne
                     \__xpg_saved_@pkgextension: {\@pkgextension}
```

I also attach the log file for more detailed perusal.  Running on macOS 14.3.1.   By reason, I am at fault, but I don’t see how.

[test.log](https://github.com/reutenauer/polyglossia/files/14313040/test.log)

**Comment by jspitz** [comment] 2024-02-16 16:14
I cannot reproduce with `polyglossia` 1.66 on current TeXLive.

In any case, the code pointed to in the error message is no longer there in the development version.

**Comment by kaimikael** [comment] 2024-02-16 17:13
I updated the collection-latex package in TeXLive, and that seems to have sorted the issue.  Whew!

**Comment by jspitz** [comment] 2024-02-16 17:52
Good. Let's close this, then.

**Closed by jspitz** 2024-02-16 17:52 UTC
Labels: FIXED IN DEV
