### ISSUE TITLE
Spurious spaces in English when French is the main language

### ISSUE THREAD

**Issue by dflipo** [reutenauer/polyglossia#66] opened 2013-12-13 10:11 UTC
Switching locally to English with \textenglish doesn't stop polyglossia to add spaces in front of ':' ';' '!' and '?' as shown in the following example:

%%%%%%%%%%%%%%%%%
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage{polyglossia}
\setmainlanguage{french}
\setotherlanguage{english}
\begin{document}
\showoutput
Texte en français: ça marche? oui! \textenglish{english: ok? no!}
\end{document}
%%%%%%%%%%%%%%%%%%%%

**Comment by hugoroy** [comment] 2015-11-13 12:28
According to the manual, \textenglish should be used for short insertions of text. So why shouldn't this work?

I can reproduce the problem.

**Comment by jspitz** [comment] 2019-08-20 08:13
The cause is the same as for #169: `\french@punctuation` remains in effect if another language is nested into french (as main language or secondary language).

Probably the only solution is to define `\nofrench@punctuation` in the style file and issue it at the very beginning of any language switch. But then, other languages might have similar hooks that need to be taken care of.

**Comment by jspitz** [comment] 2019-08-20 08:26
Having written this, a better solution seems to me to add a hook that is inserted at the beginning of a language switch (say, `\AtBeginOtherLanguage`), and then do in `gloss-french`: `\AtBeginOtherLanguage{\nofrench@punctuation}`

This seems to be a fairly generalizable solution for similar cases.

PS. I saw that there is already a hook `\xpg@hook@setlanguage`, but it seems to be reserved for external packages, and it also needs to be always redefined, so if external packages redefine this, we're lost. I'd suggest something along the line of:
```
\newcommand*{\xpg@hookii@setlanguage}{}
\newcommand\AtBeginOtherLanguage{\g@addto@macro\xpg@hookii@setlanguage}
```

**Comment by wehro** [comment] 2019-08-20 12:50
As an alternative, the following way could be chosen:
The French language module of polyglossia could check every time when a relevant punctuation mark or guillemet occurs, whether the current language is French or not. The space would only be inserted, if the language is French. For XeLaTeX, this would be easy as the current language is stored in `\languagename`.
For LuaLaTeX, the Lua variable `polyglossia.current_language` might be used, but #234 needs a fix first.

**Comment by jspitz** [comment] 2019-08-20 14:06
The alternative does not fix the general issue though: temporarily disable all language specific settings when a nested language is entered.

**Comment by jspitz** [comment] 2019-08-22 08:00
The fix seems easier than I thought. I'll di a PR in a minute.

**Comment by reutenauer** [comment] 2019-08-22 09:16
Fixed by #235.

**Closed** 2019-08-22 09:18 UTC

**Comment by ivankokan** [comment] 2019-08-22 10:40
Hi everyone, I would like to ask few questions about the general principles when switching languages:
- Should `\text<lang>` and `\begin{<lang>}` be equivalent or not?
- Assuming that `\text<lang>` activates some local language-dependent rules, how can one ensure those rules are reverted afterwards? I guess various `extras` are to be used for this purpose.
- Can someone document these `extras`: `init@extras@<lang>`, `init@noextras@<lang>`, `noextras@<lang>`, `init@noextras@<lang>`, `inlineextras@<lang>`, `inlineextras@<lang>`, `init@extras@<lang>`, `blockextras@<lang>`?

Kind regards, Ivan

**Comment by jspitz** [comment] 2019-08-22 10:48
Am Donnerstag, den 22.08.2019, 03:40 -0700 schrieb Ivan Kokan:
> Assuming that \text<lang> activates some local language-dependent
> rules, how can one ensure those rules are reverted afterwards? I
> guess various extras are to be used for this purpose.

All \*extras are reverted with \noextras, \*numbers with \no*numbers

Jürgen

**Comment by bastien-roucaries** [comment] 2019-08-22 12:07
On Thu, Aug 22, 2019 at 1:40 PM Jürgen Spitzmüller <notifications@github.com>
wrote:

> * Should `\text<lang>` and `\begin{<lang>}` be equivalent or not?
>
> The (rather sparse) documentation indicates so. But it isn't:
>
>    - \text<lang> does not change the captions, but it does change \today
>    - \begin{<lang>} changes the captions and \today
>
> As to the babel commands:
>
>    - \foreignlanguage and the starred otherlanguage environment behave
>    like \text<lang>, but in babel, \today is not changed!
>    - \selectlanguageand the unstarredotherlanguageenvironment behave like\begin{}`,
>    which is OK.
>
> The change of \extras in all commands is in line with babel.
>
> I think at least the behavior of \foreignlanguage and the starred
> otherlanguage environment should be fixed, and the documentation
> elaborated. But this should go to a separate ticket.
>


Babel documentation state it is a mess.

In think that \foreignlanguage and otherlanguage* and \textlang should
behave the same way.

For me the today stuff is a bug in polyglossia

**Comment by jspitz** [comment] 2019-08-22 12:11
This is now #239.
