### ISSUE TITLE
\bengalinumeral is corrupted. 

### ISSUE THREAD

**Issue by RezwanArefin01** [reutenauer/polyglossia#381] opened 2020-01-09 02:50 UTC
I think the `\bengalinumeral` macro from file `tex/gloss-bengali.ldf` is not working. Consider this: 
```
\documentclass[12pt]{memoir}
\usepackage{polyglossia}
\setmainlanguage[numerals=Bengali]{bengali}
\newfontfamily\bengalifont[Script=Bengali]{Kalpurush}

\begin{document}
\chapter{Hello}
\end{document}
```
This results in error `You can't use 'macro parameter character #' after \the \end{document}`. Basically whenever I use the `\bengalinumeral` macro, I get this error. Also, when I set option `changecounternumbering=true` I get bunch of more errors like this, as the options uses the `\bengalinumeral` several times. 

I've traced the problem back to this commit: 4bd37498355a8549afebe65d3c74f080a43a69aa 
It seems like line 128 -- `\def\bengalinumeral#1{\expandafter\bengalinumber\expandafter{\the##1}}` -- is doing something wrong. Reverting it back to the previous one -- `\def\bengalinumeral#1{\bengalinumber{\csname c@#1\endcsname}}` -- seems to work properly. 

Any idea what is happening wrong? Please look into the issue.

**Comment by jspitz** [comment] 2020-01-09 08:16
Your testcase compiles without error here.

**Comment by jspitz** [comment] 2020-01-09 13:46
Crucial for reproducing the problem is the changecounternumbering option. This fails for me as well:
```tex
\documentclass[12pt]{memoir}
\usepackage{polyglossia}
\setmainlanguage[numerals=Bengali,changecounternumbering=true]{bengali}
\newfontfamily\bengalifont[Script=Bengali]{Kalpurush}

\begin{document}
\chapter{Hello}
\end{document}
```

**Comment by jspitz** [comment] 2020-01-09 13:56
Should be fixed properly now.

**Closed** 2020-01-09 13:56 UTC
