### ISSUE TITLE
Error when loading Hungarian language

### ISSUE THREAD

**Issue by Drkazmer** [reutenauer/polyglossia#388] opened 2020-01-29 21:38 UTC
I get errors when loading Hungarian language using the following piece of code:

```
\documentclass[a4paper,12pt,twoside]{article}
\usepackage[margin=2.5cm]{geometry}
\usepackage{polyglossia}
\setmainlanguage{hungarian}
\begin{document}
Példa.
\end{document}
```

See also on TeX SE: https://tex.stackexchange.com/questions/526213/hungarian-polyglossia-error

**Comment by eg9** [comment] 2020-01-29 21:39
See the fix in https://tex.stackexchange.com/a/526218/4427

**Comment by jspitz** [comment] 2020-01-30 07:31
This should actually be fixed in polyglossia 1.47 which has been released to CTAN yesterday,

**Closed by jspitz** 2020-01-30 07:31 UTC

**Comment by jspitz** [comment] 2020-01-30 07:54
For the record this is a duplicate of #373. The fix was pushed at 902dabaec296.

**Comment by Drkazmer** [comment] 2020-01-30 20:19
@jspitz In the MikTeX package browser I still see 1.46. Should I do something to have the new version?

**Comment by jspitz** [comment] 2020-01-31 04:39
You probably need to wait until MikTeX catches up.
