### ISSUE TITLE
\setdefaultlanguage modify my fontfamily

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [reutenauer/polyglossia#127] opened 2016-01-26 15:15 UTC
Could you please check and join this dicussion https://tex.stackexchange.com/questions/289412/why-does-setdefaultlanguage-modify-my-fontfamily.

Somebody pointed out this could be a bug. See this code for example.

```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[spelling=new]{german}

\renewcommand*\familydefault{\sfdefault}
\begin{document}
test
\end{document}
```

"test" here is not written in `sffamily` - `rmfamily` is used instead.
When you kill `\setdefaultlanguage' it works as expected.

I am using TeX Live from CTAN (last update 3 weeks ago) with XeLaTeX on a Ubuntu 14.04.3 LTS.

**Comment by buhtz** [comment] 2016-07-14 10:09
So what is the matter with that Issue? It is not triaged for a half year.

**Comment by eg9** [comment] 2016-07-15 07:56
```
\documentclass{article}
\usepackage{polyglossia}
\setdefaultlanguage[spelling=new]{german}

\AtBeginDocument{%
  \renewcommand\familydefault{\sfdefault}\normalfont
}
\begin{document}

test

\end{document}
```

**Comment by buhtz** [comment] 2016-07-15 09:28
What is the difference?

**Comment by eg9** [comment] 2016-07-15 17:51
@buhtz 

I'm not sure what's your attitude towards me. But the code is self-explaining: the redefinition of `\familydefault` should be done at begin document and `\normalfont` must be issued to make the first font setup.

**Comment by niklasholm** [comment] 2016-08-26 10:16
> Anyway, wouldn't
> `\setmainfont{Latin Modern Sans}`
> be easier?

Since `\setmainfont` sets `\rmdefault` instead of `\sfdefault` that's a workaround, but not a proper solution. The issue here is that polyglossia does not respect the `\familydefault` setting if it changes after polyglossia was loaded.

> [...] `\normalfont` must be issued to make the first font setup

Another workaround, not mentioned in the documentation (which it should be if it's indeed required by design).

**Comment by jspitz** [comment] 2019-08-27 13:19
It's fixed in the next version.

**Closed** 2019-08-27 13:19 UTC

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2019-08-27 14:26
Thank you very much

**Comment by mitinarseny** [comment] 2019-10-28 17:26
> It's fixed in the next version.

New version was released yesterday, but it is not available to update package to this version with:
```
sudo tlmgr update polyglossia
```
Am I doing it right?

**Comment by jspitz** [comment] 2019-10-28 19:43
Be patient, it might take some days to reach all mirror servers.
