### ISSUE TITLE
Polyglossia breaks `\familydefault` when `\setmainlanguage` is used

### ISSUE THREAD

**Issue by MaxNoe** [reutenauer/polyglossia#186] opened 2017-07-15 06:48 UTC
Consider the following minimal example:

```latex
\documentclass{scrartcl}

\usepackage{fontspec}
\usepackage{polyglossia}
% \setmainlanguage{english}

\renewcommand{\familydefault}{\sfdefault}

\begin{document}
Hello World
\end{document}
```

Without `\setmainlanguage{english}`
![without_english](https://user-images.githubusercontent.com/5488440/28237209-fb513c8c-6974-11e7-86d6-68c0be0ee9a3.png)

With `\setmainlanguage{english}`

![with_english](https://user-images.githubusercontent.com/5488440/28237211-1461327c-6975-11e7-9331-0ad8583d549d.png)

**Comment by jspitz** [comment] 2019-08-23 14:43
Duplicate of #127.

**Closed** 2019-08-23 18:01 UTC
