### ISSUE TITLE
enable BCP-47 language codes

### ISSUE THREAD

**Issue by ousia** [reutenauer/polyglossia#105] opened 2015-08-10 18:57 UTC
@reutenauer, could you enable the loading of BCP-47 language codes in polyglossia?

In the meantime, I have another question (which is specific for pandoc).

For British English (among others), pandoc template for ConTeXt has defined a language synonym, such as:

``` tex
\installlanguage [en-GB] [uk]
```

For babel, it is possible to define language synonyms, such as in:

``` tex
\DeclareOption{en-GB}{\def\CurrentOption{UKenglish}%
   \bbl@load@language{english}}
```

Would it be possible to have something similar for polyglossia? (I mean, before this feature is implemented.)

**Comment by jspitz** [comment] 2019-09-14 07:04
This is a duplicate of #226. This one is older, but #226 has the detailed discussion.

**Closed by jspitz** 2019-09-14 07:04 UTC
Labels: BCP47, Feature request
